language: python
python:
 - "3.5"

services:
 - docker

before_install:
- docker pull redis
- docker run -p 6379:6379 --name redisTest redis

install:
 - pip3 install -r requirements.txt
 
script:
 - pytest
